---
title: "week4_exercises"
author: "Louis"
date: "01/11/2020"
output:
  word_document: default
  html_document: default
---

# Libraries and load data
```{r} 
#, include=FALSE}
library(sdamr)
library(tidyverse)
library(Hmisc)

# data("speeddate")
load("data/speeddate.rda")
utils::head(speeddate)# %>% html()
```
# Create model with interaction

```{r model1}
modg<-lm(other_like ~ other_attr*other_intel + other_fun*other_intel, data=speeddate)
summary(modg)
```
## Equivalent tests with $F$ statistic
```{r anova}
car::Anova(modg, type=3)
```

## Namespaces
```{r namespace}
library(dplyr)
head<-function(x, na.rm=FALSE) {
  return("Where's your head?")
}
head(speeddate)

```

# Centering
```{r Centering}
# Center other_like variable and store in new column
speeddate$other_like_c <- speeddate$other_like - mean(speeddate$other_like, na.rm=TRUE)

# With a function
center<-function(x) {
  scale(x, center=TRUE, scale=FALSE)
}

# Estimate centered model
modg_c <- lm(other_like ~ center(other_attr)*center(other_intel) + center(other_fun)*center(other_intel), data=speeddate)
summary(modg_c)

```
# Mediation
## Import data
```{r legacydata}

library(readr)
legacy2015 <- read_csv("~/codes/stats/r/data/legacy2015.csv")
head(legacy2015)
```
```{r medmod1}
mod1 <- lm(donation ~ legacy, data = legacy2015)
mod2 <- lm(intention ~ legacy, data = legacy2015)
mod3 <- lm(donation ~ intention + legacy, data = legacy2015)
```

## bootstrap mediation test with 2000 simulations
```{r med1}
# install.packages("mediation")
set.seed(20201027)
med <- mediation::mediate(model.m = mod2, model.y = mod3, sims = 2000, boot = TRUE, boot.ci.type = "bca", treat = "legacy", mediator = "intention")
summary(med)
```
# Problems from problem class

```{r problems}
# Read csv view head
redist2015<-read_csv("~/codes/stats/r/data/redist2015.csv")
head(redist2015)
```

## 1.

```{r 1r}
# 1. 
library(GGally)
ggpairs(redist2015[,c("income", "SC_mean", "redist")], upper=list(continuous= wrap(ggally_cor, size=3.5, family="sans")))
```

## 2.

```{r 2r}
# 3 Models to assess whether the effect of income on redist is mediated by SC_mean
mod1 <- lm(redist ~ income, data=redist2015)
mod2 <- lm(SC_mean ~ income, data = redist2015)
mod3 <- lm(redist ~ income + SC_mean, data = redist2015)

summary(mod1)
summary(mod2)
summary(mod3)

## mod1 - income has a significant negative correlation with redist
## mod2 - income has a signifcant positive correlation with SC_mean
## mod3 - There is a significant unique effect of SC_mean on redist when controlling for income
##        but no significant unique effect of income (< 0.1)
## Therefore we can say that there is a full mediation of the effect of income via SC_mean on redist.


```

## 3.
Non parametric bootstrap analysis of the mediated effect of income on redist
```{r 3r}
set.seed(20201027)
med <- mediation::mediate(model.m = mod2, model.y = mod3, sims = 1000, boot = TRUE, boot.ci.type = "bca", treat = "income", mediator = "SC_mean")
summary(med)
```
## 4. 

```{r 4r}

mod1c <- lm(redist ~ income + pol_att + age, data=redist2015)
mod2c <- lm(SC_mean ~ income + pol_att + age, data = redist2015)
mod3c <- lm(redist ~ income + SC_mean + pol_att + age, data = redist2015)

summary(mod1c)
summary(mod2c)
summary(mod3c)


set.seed(20201027)
med <- mediation::mediate(model.m = mod2c, model.y = mod3c, sims = 1000, boot = TRUE, boot.ci.type = "bca", treat = "income", mediator = "SC_mean")
summary(med)


```
## Further analyses
1. 
```{r}

summary(lm(PD_fair ~ PD_gini+PD_mean+pol_att, data=redist2015))

# Interaction effect?
summary(lm(PD_fair ~ PD_gini*PD_mean + pol_att, data=redist2015))



```

```{r}
library(sdamr)

summary(lm(PD_fair ~ center(PD_gini) + center(PD_mean) + center(pol_att), data=redist2015))

```

```{r 7r}
mod1 <- lm(redist ~ PD_mean + income+pol_att+age, data=redist2015)
summary(mod1)
mod2 <- lm(PD_fair ~ PD_mean + income+pol_att+age, data=redist2015)
summary(mod2)
mod3 <- lm(redist ~ PD_mean + PD_fair+income+pol_att+age, data=redist2015)
summary(mod3)

set.seed(20201027)
med <- mediation::mediate(model.m = mod2, model.y = mod3, sims = 1000, boot = TRUE, boot.ci.type = "bca", treat = "PD_mean", mediator = "PD_fair")
summary(med)

## Evidence for full mediation of via PD_fair of PD_mean on redist
```

