print("-------")
library(ggplot2)
attach(mtcars)
par(mfrow=c(2,2))
df <- data.frame(a1, a2, a3, a4)

a1 <- rbinom(20, 8, 0.5)
mean(a1)
median(a1)
sample_mode(a1)
sample_sd(a1)
IQR(a1)
sub1 <- paste("Mean: ", mean(a1), "Median: ", median(a1), "Mode: ", sample_mode(a1), "IQR: ", IQR(a1), sep=" ")
hist(a1, breaks=8, main="20 trials of 8 guesses", sub=sub1, xlab="Correct guesses")

a2 <- rbinom(20, 8, 0.5)
mean(a2)
median(a2)
sample_mode(a2)
sample_sd(a2)
IQR(a2)
sub2 <- paste("Mean: ", mean(a2), "Median: ", median(a2), "Mode: ", sample_mode(a2), "IQR: ", IQR(a2), sep=" ")
hist(a2, breaks=8, main="20 trials of 8 guesses", sub=sub2,xlab="Correct guesses")

a3 <- rbinom(20, 10000, 0.5)
mean(a3)
median(a3)
sample_mode(a3)
sample_sd(a3)
IQR(a3)
sub3 <- paste("Mean: ", mean(a3), "Median: ", median(a3), "Mode: ", sample_mode(a3), "IQR: ", IQR(a3), sep=" ")
hist(a3, breaks=10000, main="20 trials of 10,000 guesses", sub=sub3, xlab="Correct guesses")

a4 <- rbinom(10000, 20, 0.5)
mean(a4)
median(a4)
sample_mode(a4)
sample_sd(a4)
IQR(a4)
sub4 <- paste("Mean: ", mean(a4), "Median: ", median(a4), "Mode: ", sample_mode(a4), "IQR: ", IQR(a4), sep=" ")
hist(a4, breaks=20, main="10,000 trials of 20 guesses", sub=sub4, xlab="Correct guesses")

ggplot(df, aes(x=a1)) + geom_histogram(bins=8, colour="black", fill='#8C8279') + xlab("Correct guesses")

#?sample_mode
